language: python
install: make minimal
script: make test
after_success: venv/bin/coveralls
sudo: false
cache:
    directories:
        - $HOME/venv
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
